### ISSUE TITLE
500 errors when entering preferences after setting the display language

### ISSUE THREAD

**Issue by wenxuanjun** [asciimoo/searx#1505] opened 2019-02-02 05:40 UTC
After I set the display language to Chinese in the preferences and then opened the preferences after setting, I got an 500 Internal Serve Error.

Error log:
```
ERROR:flask.app:Exception on /preferences [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "searx/webapp.py", line 725, in preferences
    preferences=True)
  File "searx/webapp.py", line 400, in render
    '{}/{}'.format(kwargs['theme'], template_name), **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/build/searx/searx/templates/oscar/preferences.html", line 2, in top-level template code
    {% extends "oscar/base.html" %}
  File "/root/build/searx/searx/templates/oscar/base.html", line 82, in top-level template code
    {% block content %}
  File "/root/build/searx/searx/templates/oscar/preferences.html", line 78, in block "content"
    {% set method_info = _('Change how forms are submited, <a href="http://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Request_methods" rel="external">learn more about request methods</a>') %}
  File "/usr/lib/python2.7/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
  File "/usr/lib64/python2.7/site-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/usr/lib64/python2.7/site-packages/markupsafe/__init__.py", line 293, in <lambda>
    __float__ = lambda s: float(s.obj)
TypeError: float() argument must be a string or a number
```
The system is Ubuntu 16.04,Python 2.7.5

**Comment by wenxuanjun** [comment] 2019-02-02 05:54
The theme is oscar

**Comment by bourrel** [comment] 2019-02-04 09:19
Duplicate of #1502

**Closed** 2019-04-09 06:57 UTC
Labels: duplicate
